names="Harshita,Akshat"
print(names[0:15])
l1=len("mango")
print("Mango is a ",l1,"letter word")
print(names[:])
print(names.lower())
print(names.upper())
print(names.rstrip("t"))
print(names.replace("Akshat","Harshita"))
print(names.split(","))
print(names.capitalize())
print(names.center(50))
print(names.count("Akshat"))
str1='Hi'
print(str1.isalnum())
print(str1.isalpha())
print(str1.endswith("i"))
print(str1.isupper())
str2="Good Morning"
print(str2[4].isspace())
print(str2.istitle())
print(str2.startswith("Good"))
print(str2.title())
print(str2.swapcase())